[package]
name = "advent_of_code_rust"
version = "1.0.0"
authors = ["Oliver Dunk <oliver@oliverdunk.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
regex = "1"
lazy_static = "1.4.0"
